# Generated by Django 4.0.2 on 2024-03-05 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0020_profile_facebook_url_profile_instragram_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='x_url',
            new_name='LinkedIn_url',
        ),
    ]
