# Generated by Django 4.0.2 on 2024-03-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0022_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='instragram_url',
            new_name='instagram_url',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='LinkedIn_url',
            new_name='linkedin_url',
        ),
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/profile/'),
        ),
    ]
